title: Constantin Kronbichler
site_title: '@ccrownhill - Constantin Kronbichler'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ccrownhill
email: "ckronbichler at proton dot me"

# absolute or relative
profile_picture: assets/images/pp.jpg


about_paragraphs:
  - "I am an autodidact, interested in everything from psychology to software
    development."
  - "\"what I cannot create, I do not understand\" (Richard Feynman) is the guiding
    principle for my projects, as they seek to teach me by building as much
    as possible from scratch without relying on big libraries."

skills_left:
  - name: c++
    percent: 95
  - name: python
    percent: 95
  - name: functional programming (f#)
    percent: 75
  - name: go
    percent: 90
  - name: pytorch
    percent: 95
  - name: tensorflow
    percent: 60
  - name: large language models
    percent: 60

skills_right:
  - name: geometric deep learning
    percent: 80
  - name: computer vision
    percent: 80
  - name: reinforcement learning
    percent: 55
  - name: docker
    percent: 85
  - name: linux/unix command line and shell scripting
    percent: 95
  - name: web front-end (html/css/javascript)
    percent: 85
  - name: web back-end (nodejs and go)
    percent: 80
