title: Constantin Kronbichler
site_title: '@ccrownhill - Constantin Kronbichler'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ccrownhill
email: "ckronbichler at proton dot me"

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
