title: Constantin Kronbichler
site_title: '@ccrownhill - Constantin Kronbichler'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ccrownhill
email: "ckronbichler at proton dot me"

# absolute or relative
profile_picture: assets/images/pp.jpg


about_paragraphs:
  - "I am an autodidact, interested in almost everything, from psychology to software
    development."
  - "\"what I cannot create, I do not understand\" (Richard Feynman) is the guiding
    principle for my projects, as they seek to teach me by building as much
    as possible from scratch, without relying on big libraries."

skills_left:
  - name: c++
    percent: 95
  - name: python
    percent: 95
  - name: functional programming (f#)
    percent: 75
  - name: go
    percent: 87
  - name: pytorch
    percent: 95
  - name: tensorflow
    percent: 60
  - name: large language models
    percent: 65

skills_right:
  - name: geometric deep learning
    percent: 90
  - name: computer vision
    percent: 90
  - name: reinforcement learning
    percent: 60
  - name: docker
    percent: 90
  - name: linux/unix command line and shell scripting
    percent: 95
  - name: web front-end (html/css/javascript)
    percent: 80
  - name: web back-end (nodejs and go)
    percent: 80


projects:
  - name: "matrix_gpu - custom gpu+compiler for linear algebra on fpga"
    image: "/portfolio/assets/images/matrix_gpu.png"
    details:
      - started as a group project at Imperial College where I did some of the gpu design and
        a compiler for creating machine code to plot functions
      - later I came up with my own linear algebra language to utilise
        gpu for parallel multi-dimensional array operations
      - added this into the compiler
      - added garbage collection to the compiler
    tags: "systemverilog, c++, neural networks, gpu, fpga, compiler"
    github: matrix_gpu
  - name: "auto_derivator - auto differentiation and neural network library"
    image: "/portfolio/assets/images/auto_derivator.png"
    details:
      - automatic gradient computation with reverse gradient accumulation
      - added PyTorch-like neural network frontend
    tags: "c++, backpropagation, graphs"
    github: auto_derivator
  - name: "nonaginta_comp - c90 to risc-v compiler"
    image: "/portfolio/assets/images/nonaginta_comp.jpg"
    details:
      - created as a pair project at Imperial College
      - implement almost all c90 features
      - utilises llvm-ir-like intermediate representation for enabling optimisations
        in the future
      - ir represented as a control flow graph
    tags: "compiler, c++, risc-v"
    github: nonaginta_comp
  - name: "riscv_cpu - pipelined risc-v cpu with multilevel-caching in systemverilog"
    image: "/portfolio/assets/images/riscv_cpu.png"
    details:
      - "created as a group project at Imperial College; I did the following:"
      - 5 stage pipelining with forwarding, branch prediction, hazard detection
      - multilevel caching with split l1 cache and shared l2 cache + main memory with a snooping protocol for cache coherency
    tags: "systemverilog, cpu, risc-v"
    github: riscv_cpu
  - name: "serpens_os - x86 operating system for playing snake"
    image: "/portfolio/assets/images/serpens_os.png"
    details:
      - built with cross-compiler and tested in QEMU and on laptop
      - write bootloader in nasm assembly
      - drivers for keyboard, display using interrupt handling
    tags: "c, os, bare metal, x86"
    github: serpens_os
  - name: "parvum_parse - pipelined risc-v cpu with multilevel-caching in systemverilog"
    image: "/portfolio/assets/images/parvum_parse.png"
    details:
      - LR(1) shift reduce parser to parse input with yacc/bison-like file specifying grammar and reduction rules
      - obtained grammar file representation as the "canonical collection of sets"
        along with a set transition table to represent the whole graph structure
      - generated parse table from it
      - had to implement my own hash maps since this was written in c only
      - uses tokens from lex as input
    tags: "finite automata, parsing, c"
    github: parvum_parse

open_source_work:
  - name: clang
    details:
      - fix a bug where an error was not given when using a non-defined (but
        declared) identifier
      - added error message for this
      - worked with the c standard to test all edge cases where this should
        and shouldn't result in an error
    tags: "compiler, c++"
    github: "https://github.com/llvm/llvm-project/"
  - name: issie
    details:
      - issie is a digital circuit simulation tool used for teaching
      - wrote functional F# code using an F#/Elmish/Fable/Electron tool chain
      - added concurrency to Issie using web workers and explore web worker
        bandwidth and latency
    tags: "functional programming (f#), concurrency"
    github: "https://github.com/tomcl/issie/"
